### PR TITLE
Update + Parallax Update

### PR DESCRIPTION
**Pull request by Elias2660**

### CODE REVIEW

**Comment by Elias2660** [comment]
@TheEgghead27

**Comment by TheEgghead27** [comment]
@Elias2660 [redeployed](https://junior.stuysu.org/), let me know if this looks right (since we've changed the process for builds to use `docker compose`)

**Comment by Elias2660** [comment]
looks good, few bugs but overall ok

**Comment by TheEgghead27** [comment]
Bugs on our end, or yours?

**Comment by Elias2660** [comment]
on my end; we haven't fixed all the bugs yet

**Comment by Elias2660** [comment]
your end is good :)

**Pull request merged**
